#!/bin/sh
var1=25
var2=30
var3=World
name=Deepak
var4=`pwd`

echo "Value 1 + Value 2 = " $var1 + $var2 = `expr $var1 + $var2`
echo '\e[1;30mHello' $var3'\e[m \nI am '$name

echo "\e[1;33m-----\e[m"
echo "\e[1;34m-----\e[m"
echo "\e[1;35m-----\e[m"
echo "\e[1;36m-----\e[m"

echo "\e[1;43m-----\e[m"
echo "\e[1;44m-----\e[m"
echo "\e[1;45m-----\e[m"
echo "\e[1;46m-----\e[m"

time du -ch | grep total
